command_timeout = 2000

[directory]
format = "[ ï±® $path]($style)[$read_only]($read_only_style) "
style = "fg:bright-blue"
fish_style_pwd_dir_length = 3

[git_branch]
symbol = "îœ‰ ï˜ "

[cmd_duration]
format = "[ ï™ $duration ]($style)"
style = "fg:bright-white"

[character]
success_symbol = '[ âœ](bold green) '
error_symbol = '[ âœ—](#E84D44) '

[time]
# disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:bright-white"
format = '[ ó±‘ $time ]($style)'

[os]
disabled = false

[direnv]
disabled = false

[shell]
disabled = false
format = '[$indicator]($style) '
style = 'bold yellow'

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false
